import MindElixir from '../src'
import type { MindElixirData, NodeObj, Options } from '../src'

type Metadata = {
  refId: string
  priority?: number
}

declare const options: Options<Metadata>
declare const data: MindElixirData<Metadata>

const mind = null as unknown as MindElixir<Metadata>
const initialized: ReturnType<MindElixir<Metadata>['init']> = mind.init(data)
const result: MindElixirData<Metadata> = mind.getData()
const metadata: Metadata | undefined = result.nodeData.metadata
const child: NodeObj<Metadata> | undefined = result.nodeData.children?.[0]

// `diffRefresh` is installed by `init` and always present, so it is declared
// without `?`. Keeping the assertion here guards the declaration itself: the
// member block in `src/index.ts` is partly regenerated by `gen-members.js`, and
// losing the declaration would otherwise only surface as a compile error in a
// user's project. The argument type proves the generic flows through.
const patched: boolean = mind.diffRefresh(data)

void options
void initialized
void metadata
void child
void patched
